import XCTest
@testable import neo_wake_ios

// Replays Fixtures/wakeword/chorus6_stream_golden.json (generated by
// `script/chorus6_reference.py` in the app repo from the bundle's own
// held-out positives, padded with 1.5 s / 2.5 s of silence and scored by the
// real chorus6 graphs on a laptop) through the real WakeSpotter gate with a
// fake body hook that hands back each hop's recorded wake score.
//
// A green run proves the gate (two-hop confirm, hysteresis re-arm, ring
// reset on fire) reproduces the reference rig's fire sequence hop-for-hop.
// The ONNX numerics themselves are the device-gated section at the bottom
// (real sessions, real wavs; ORT ships no simulator slice).
//
// Resource loading: resolved relative to this source file via `#filePath`,
// which survives both `swift test` and a host-run Xcode logic test.
private struct GoldenStream {
    let hopScores: [Double]
    let expectedFireHop: Int
    let fires: [Int]
}

private struct GoldenFixture {
    let threshold: Double
    let release: Double
    let streams: [String: GoldenStream]
    let wholeWindow: [String: Double]
}

private func fixturesDir() -> URL {
    URL(fileURLWithPath: #filePath).deletingLastPathComponent().appendingPathComponent("Fixtures/wakeword")
}

private func loadFixture() -> GoldenFixture {
    let data = try! Data(contentsOf: fixturesDir().appendingPathComponent("chorus6_stream_golden.json"))
    let json = try! JSONSerialization.jsonObject(with: data) as! [String: Any]
    let rawStreams = json["streams"] as! [String: [String: Any]]
    let streams = rawStreams.mapValues { v -> GoldenStream in
        GoldenStream(
            hopScores: (v["hop_scores"] as! [NSNumber]).map { $0.doubleValue },
            expectedFireHop: (v["expected_fire_hop"] as! NSNumber).intValue,
            fires: (v["fires"] as! [NSNumber]).map { $0.intValue }
        )
    }
    let wholeWindow = (json["whole_window"] as! [String: [String: Any]]).mapValues { ($0["wake_score"] as! NSNumber).doubleValue }
    return GoldenFixture(
        threshold: (json["threshold"] as! NSNumber).doubleValue,
        release: (json["release"] as! NSNumber).doubleValue,
        streams: streams,
        wholeWindow: wholeWindow
    )
}

final class WakeSpotterGoldenTest: XCTestCase {
    func testFixtureSanity_coversBothOrdersAndFiveReferenceInputs() {
        let fixture = loadFixture()
        XCTAssertEqual(Set(fixture.streams.keys), ["positive_wake_up_neo", "positive_neo_wake_up"])
        XCTAssertEqual(Set(fixture.wholeWindow.keys),
                       ["positive_wake_up_neo", "positive_neo_wake_up", "burst_-30dBFS", "burst_-45dBFS", "silence"])
        XCTAssertEqual(fixture.threshold, 0.45, accuracy: 1e-9)
        XCTAssertEqual(fixture.release, WakeSpotter.releaseFraction * fixture.threshold, accuracy: 1e-6)
        XCTAssertGreaterThan(fixture.wholeWindow["positive_wake_up_neo"]!, 0.9)
        XCTAssertGreaterThan(fixture.wholeWindow["positive_neo_wake_up"]!, 0.65)
        XCTAssertLessThan(fixture.wholeWindow["silence"]!, 0.05)
        XCTAssertLessThan(fixture.wholeWindow["burst_-30dBFS"]!, 0.05)
        XCTAssertLessThan(fixture.wholeWindow["burst_-45dBFS"]!, 0.05)
    }

    func testReplayingEachPositiveTrace_firesExactlyOnceAtRecordedHop() throws {
        let fixture = loadFixture()
        for (name, stream) in fixture.streams {
            var hop = 0
            let spotter = WakeSpotter(
                threshold: fixture.threshold,
                frontend: { _ in [Float](repeating: 0, count: WakeSpotter.logmelFloats) },
                body: { _ in
                    let s = Float(stream.hopScores[hop])
                    hop += 1
                    // Split the recorded sum across the two wake classes so the
                    // gate is proven on the sum, not on one class.
                    return [1 - s, s * 0.6, s * 0.4]
                }
            )
            var fired: [Int] = []
            for i in 0..<stream.hopScores.count {
                let step = try spotter.process([Int16](repeating: 0, count: WakeSpotter.advanceSamples))
                XCTAssertEqual(step.stepIndex, i)
                XCTAssertEqual(step.score!, stream.hopScores[i], accuracy: 1e-5, "\(name) hop \(i)")
                if step.fired { fired.append(i) }
            }
            XCTAssertEqual(fired, [stream.expectedFireHop], "\(name): exactly one fire at the recorded hop")
            XCTAssertEqual(fired, stream.fires, "\(name): the rig recorded the same fire list")
            XCTAssertEqual(stream.expectedFireHop, 38, "\(name): the hop ending 3120 ms")
        }
    }

    // MARK: - Device-gated (real ORT sessions; ORT ships no simulator slice)

    private func loadWav(_ name: String) throws -> [Int16] {
        let data = try Data(contentsOf: fixturesDir().appendingPathComponent("\(name).wav"))
        XCTAssertGreaterThan(data.count, 44)
        return data.dropFirst(44).withUnsafeBytes { raw in
            Array(raw.bindMemory(to: Int16.self)).map { Int16(littleEndian: $0) }
        }
    }

    /// Streams `pcm` padded with 1.5 s / 2.5 s of silence through the real
    /// chain at threshold 0.45 and returns the fired hop indices.
    private func streamOnDevice(_ pcm: [Int16]) throws -> [Int] {
        try NeoWakeSessions.shared.ensureInitialized()
        let spotter = WakeSpotter(threshold: 0.45, frontend: NeoWakeOrtHooks.frontendHook(), body: NeoWakeOrtHooks.bodyHook())
        let padded = [Int16](repeating: 0, count: 24000) + pcm + [Int16](repeating: 0, count: 40000)
        var fired: [Int] = []
        var hop = 0
        var start = 0
        while start + WakeSpotter.advanceSamples <= padded.count {
            let step = try spotter.process(Array(padded[start..<(start + WakeSpotter.advanceSamples)]))
            if step.fired { fired.append(hop) }
            hop += 1
            start += WakeSpotter.advanceSamples
        }
        return fired
    }

    func testDevice_positiveWakeUpNeo_firesOnceAtHop38() throws {
        #if !os(iOS) || targetEnvironment(simulator)
        throw XCTSkip("ORT has no simulator/host slice — device only")
        #else
        let fired = try streamOnDevice(try loadWav("positive_wake_up_neo"))
        XCTAssertEqual(fired.count, 1)
        XCTAssertEqual(abs(fired[0] - 38) <= 1, true, "fire within one hop of the laptop reference")
        #endif
    }

    func testDevice_positiveNeoWakeUp_firesOnce() throws {
        #if !os(iOS) || targetEnvironment(simulator)
        throw XCTSkip("ORT has no simulator/host slice — device only")
        #else
        XCTAssertEqual(try streamOnDevice(try loadWav("positive_neo_wake_up")).count, 1)
        #endif
    }

    func testDevice_silence_neverFires() throws {
        #if !os(iOS) || targetEnvironment(simulator)
        throw XCTSkip("ORT has no simulator/host slice — device only")
        #else
        XCTAssertEqual(try streamOnDevice([Int16](repeating: 0, count: 32000)), [])
        #endif
    }
}
