import XCTest
@testable import neo_wake_ios

// Replays test/fixtures/wakeword/golden_vectors.json (mirrored here as
// Fixtures/wakeword/golden_vectors.json) -- generated by
// `python script/wakeword_reference.py --synth 64000 --threshold 0.3
// --out test/fixtures/wakeword/golden_vectors.json` in the app repo -- through
// the real WakeSpotter, pinning the chain's stride/buffer/ring COUNTS against
// the Python reference rig's own bookkeeping (KTD7, evidence for R7).
//
// 1:1 port of `test/core/neo_agent/wake_spotter_golden_test.dart` -- read
// that file's header before trusting a green run here for more than it
// proves. Short version: the fixture is a deterministic synthetic signal,
// not speech. A green run here proves the mel buffer fills to exactly 76
// frames, the embedding ring fills to exactly 16, and `process` passes the
// classify hook's return straight through as its score with no extra
// transform -- on the SAME steps the Python rig recorded. It does NOT and
// CANNOT prove the chain fires on real speech, or the fire-lag figure R13
// asks for. Both need a real "Neo SimSim" recording -- see the skipped tests
// at the bottom of this file.
//
// The mel and embed hooks below are STUBS, not golden numbers: raw per-step
// mel values aren't in golden_vectors.json (only mel_frames_added, a
// constant 8, is -- asserted below), and embed is substituted wholesale with
// the fixture's recorded embeddings regardless of what the mel hook returns.
// Real per-step ONNX numerics are U6's other half, not this file's job.
//
// Like WakeSpotterTests.swift (U3), this needs no native ORT/plugin --
// mel/embed/classify are injected hooks -- so it runs as a standalone SwiftPM
// package mirroring these exact production sources (`swift test`), not
// through a wired Xcode target (no example app in this checkout yet).
//
// Resource loading: no XCTest bundle/resource mechanism exists in this
// checkout (see WakeSpotterTests.swift's note), so the fixture is resolved
// relative to this source file via `#filePath`, which survives both `swift
// test` and a host-run Xcode logic test where the checkout is still on disk.

private struct GoldenStep {
    let melFramesAdded: Int
    let embeddingPresent: Bool
    let embedding: [Double]?
    let score: Double?
}

private struct GoldenFixture {
    let threshold: Double
    let inputSource: String
    let steps: [GoldenStep]
}

private func loadFixture() -> GoldenFixture {
    let url = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .appendingPathComponent("Fixtures/wakeword/golden_vectors.json")
    let data = try! Data(contentsOf: url)
    let json = try! JSONSerialization.jsonObject(with: data) as! [String: Any]
    let input = json["input"] as! [String: Any]
    let rawSteps = json["steps"] as! [[String: Any]]

    let steps = rawSteps.map { step -> GoldenStep in
        let embeddingPresent = step["embedding_present"] as! Bool
        let embedding = (step["embedding"] as? [Any])?.map { ($0 as! NSNumber).doubleValue }
        let score = (step["score"] as? NSNumber)?.doubleValue
        return GoldenStep(
            melFramesAdded: (step["mel_frames_added"] as! NSNumber).intValue,
            embeddingPresent: embeddingPresent,
            embedding: embedding,
            score: score
        )
    }

    return GoldenFixture(
        threshold: (json["threshold"] as! NSNumber).doubleValue,
        inputSource: input["source"] as! String,
        steps: steps
    )
}

final class WakeSpotterGoldenTest: XCTestCase {
    func testFixtureSanity_syntheticInput_longEnoughToPassWarmUp() throws {
        let fixture = loadFixture()
        XCTAssertEqual(fixture.inputSource, "synth")
        // Warm-up needs 25 steps (76-frame mel fill + 16-embedding ring); demand
        // real margin past it so a shrunk fixture would fail loudly here first.
        XCTAssertGreaterThanOrEqual(fixture.steps.count, WakeSpotter.embeddingRingDepth + 10)
    }

    func testReplayingFixture_reproducesFrameAndEmbeddingCountsAndScoreTrace() throws {
        let fixture = loadFixture()
        let steps = fixture.steps

        let embedStepIndices = steps.indices.filter { steps[$0].embeddingPresent }
        let scoreStepIndices = steps.indices.filter { steps[$0].score != nil }

        var embedCallIndex = 0
        var classifyCallIndex = 0

        let spotter = WakeSpotter(
            threshold: fixture.threshold,
            mel: { _ in
                [Float](repeating: 0, count: WakeSpotter.melFramesPerStep * WakeSpotter.melBinCount)
            },
            embed: { _, _ in
                // Indexing past embedStepIndices throws (crashing the test) --
                // that's the check for WakeSpotter embedding on MORE steps than
                // the fixture recorded; the count assert below catches fewer.
                let stepIndex = embedStepIndices[embedCallIndex]
                embedCallIndex += 1
                return steps[stepIndex].embedding!.map { Float($0) }
            },
            classify: { _, _ in
                let stepIndex = scoreStepIndices[classifyCallIndex]
                classifyCallIndex += 1
                return steps[stepIndex].score!
            }
        )

        for i in 0..<steps.count {
            let step = steps[i]
            // Content is irrelevant: mel is a stub and embed is substituted
            // wholesale, so no assertion here depends on these bytes.
            let frame = [Int16](repeating: 0, count: WakeSpotter.advanceSamples)
            let result = try spotter.process(frame)

            XCTAssertEqual(result.stepIndex, i)
            // Pins R3's 8-frames-per-80ms-step against the Python rig's own count.
            XCTAssertEqual(step.melFramesAdded, WakeSpotter.melFramesPerStep)

            XCTAssertEqual(
                spotter.melBufferLength == WakeSpotter.melBufferFrames,
                step.embeddingPresent,
                "step \(i): embedding_present=\(step.embeddingPresent) should match a "
                    + "full \(WakeSpotter.melBufferFrames)-frame mel buffer"
            )

            if let expectedScore = step.score {
                guard let actualScore = result.score else {
                    XCTFail("step \(i): expected a score, got nil")
                    continue
                }
                XCTAssertEqual(actualScore, expectedScore, accuracy: 1e-4, "step \(i)")
            } else {
                XCTAssertNil(result.score, "step \(i)")
            }
        }

        // Exact counts (KTD7): fewer calls than the fixture recorded would pass
        // every per-step check above yet still be a warm-up regression.
        XCTAssertEqual(embedCallIndex, embedStepIndices.count)
        XCTAssertEqual(classifyCallIndex, scoreStepIndices.count)
    }

    // R13 asks for the fire-lag figure to be RE-MEASURED, not remembered, on
    // every model swap -- these are the two tests that would do that. Written
    // here, skipped, rather than left off the plan entirely, so the gap shows
    // in `swift test`/`xcodebuild test` output instead of only in a doc.
    //
    // Unblocking needs, in order (see wake_spotter_golden_test.dart's group
    // doc comment for the full sequence):
    //   1. A real recording of "Neo SimSim" as raw 16 kHz mono signed-16-bit
    //      PCM, saved to test/fixtures/wakeword/neo_simsim_16k.pcm in the app
    //      repo (KD9 forbids this ever being a captured-on-device artifact).
    //   2. Its phrase_end_sample labelled by ear/waveform.
    //   3. Regenerate golden_vectors.json from that PCM via
    //      script/wakeword_reference.py, which fills in fire_step_index and
    //      fire_lag_ms.
    //   4. Re-copy the fixture here, un-skip these two tests, assert against
    //      those two fields.
    //
    // Do NOT fill this in with a synthesised utterance or an invented lag
    // number -- either would ship a geometry fault dressed as a passing test.
    func testFixtureIsDetectedAtConfiguredThreshold() throws {
        throw XCTSkip(
            "blocked on test/fixtures/wakeword/neo_simsim_16k.pcm; see this file's "
                + "doc comment"
        )
    }

    func testScoreCrossesThreshold_exactlyConfiguredLagAfterPhraseEnd() throws {
        throw XCTSkip(
            "blocked on test/fixtures/wakeword/neo_simsim_16k.pcm; see this file's "
                + "doc comment"
        )
    }
}
